version: '3.8'

# Exemple d'utilisation de Podman secrets avec compose
# Démonstration d'une architecture multi-conteneurs sécurisée

services:
  # Application frontend avec secrets
  app:
    build:
      context: .
      dockerfile: Dockerfile-secrets
    container_name: secure-app
    user: "1001"
    read_only: true
    security_opt:
      - no-new-privileges:true
      - seccomp=seccomp-profile.json
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp
      - /run
    secrets:
      - db_password
      - api_key
    environment:
      # Pas de secrets dans les variables d'env!
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_NAME=appdb
      # Le mot de passe est lu depuis /run/secrets/db_password
    depends_on:
      - postgres
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 100

  # Base de données PostgreSQL avec secret
  postgres:
    image: postgres:15-alpine
    container_name: secure-postgres
    user: postgres
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    tmpfs:
      - /tmp
      - /run
    secrets:
      - db_password
    environment:
      # PostgreSQL supporte nativement les secrets via fichier
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=appuser
      - POSTGRES_DB=appdb
    volumes:
      # Volume pour les données persistantes avec SELinux
      - postgres_data:/var/lib/postgresql/data:Z
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.5
    pids_limit: 50

  # Service Redis avec configuration sécurisée
  cache:
    image: redis:7-alpine
    container_name: secure-redis
    user: redis
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      - /run
      - /data
    command: >
      redis-server
      --requirepass $(cat /run/secrets/redis_password)
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
    secrets:
      - redis_password
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.5
    pids_limit: 30

# Déclaration des secrets externes
# Les secrets doivent être créés AVANT de lancer compose
secrets:
  db_password:
    external: true
    # Créer avec: echo "postgres_pass" | podman secret create db_password -

  api_key:
    external: true
    # Créer avec: echo "api_secret" | podman secret create api_key -

  redis_password:
    external: true
    # Créer avec: echo "redis_pass" | podman secret create redis_password -

# Volumes pour persistance
volumes:
  postgres_data:
    driver: local

# Réseau personnalisé pour isolation
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
